
name: "Publish"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
      - name: "Publish"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}